# Generated by Django 6.0.2 on 2026-02-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
